
import { createContext, useContext, useEffect, useState } from "react"

type Language = "es" | "en"

type LanguageProviderProps = {
    children: React.ReactNode
    defaultLanguage?: Language
    storageKey?: string
}

type LanguageProviderState = {
    language: Language
    setLanguage: (language: Language) => void
    t: (key: string) => string
}

const initialState: LanguageProviderState = {
    language: "es",
    setLanguage: () => null,
    t: (key: string) => key,
}

const translations = {
    es: {
        // Nav & Common
        dashboard: "Dashboard",
        users: "Gestión de Usuarios",
        machines: "Gestión de Máquinas",
        alerts: "Alertas",
        settings: "Configuración",
        logout: "Cerrar Sesión",
        language: "Idioma",
        theme: "Tema",
        appearance: "Apariencia",
        general: "Configuración General",
        notifications: "Notificaciones",
        security: "Seguridad",
        api: "Configuración de API",
        error: "Error",
        success: "Éxito",
        cancel: "Cancelar",
        save: "Guardar",
        save_configuration: "Guardar Configuración",
        config_saved: "Configuración guardada",
        config_saved_desc: "Los cambios han sido aplicados correctamente",
        create: "Crear",
        update: "Actualizar",
        delete: "Eliminar",
        actions: "Acciones",
        loading: "Cargando...",
        none: "Ninguno",
        all: "Todos",
        company_name: "Nombre de la Empresa",
        company_name_placeholder: "Nombre de la empresa",
        timezone: "Zona Horaria",
        refresh_interval: "Intervalo de Actualización (segundos)",
        maintenance_alerts: "Alertas de Mantenimiento",
        maintenance_alerts_desc: "Recibir notificaciones cuando se requiera mantenimiento",
        temperature_alerts: "Alertas de Temperatura",
        temperature_alerts_desc: "Notificar cuando la temperatura exceda los límites",
        daily_reports: "Reportes Diarios",
        daily_reports_desc: "Enviar resumen diario por correo electrónico",
        session_timeout: "Tiempo de Sesión (minutos)",
        "2fa": "Autenticación de Dos Factores",
        "2fa_desc": "Requerir verificación adicional para el acceso",
        audit_log: "Registro de Auditoría",
        audit_log_desc: "Mantener registro de todas las acciones del usuario",
        api_endpoint: "Endpoint de la API",
        api_endpoint_placeholder: "URL del endpoint de la API",
        api_timeout: "Timeout de API (segundos)",
        auto_retries: "Reintentos Automáticos",
        auto_retries_desc: "Reintentar automáticamente las llamadas fallidas",
        light: "Claro",
        dark: "Oscuro",
        system: "Sistema",
        general_desc: "Configuración básica del sistema",
        notifications_desc: "Configura las alertas y notificaciones del sistema",
        security_desc: "Configuración de seguridad y acceso",
        api_desc: "Configuración de conexiones externas",
        appearance_desc: "Personaliza la apariencia del sistema",

        // Login
        welcome_title: "Sistema Industrial",
        welcome_desc: "Inicia sesión para acceder al sistema",
        email: "Correo electrónico",
        password: "Contraseña",
        login_button: "Iniciar Sesión",
        login_loading: "Iniciando sesión...",
        login_error: "Error de autenticación",
        login_error_desc: "Correo o contraseña incorrectos",
        enter_email_password: "Ingresa tu correo y contraseña",
        email_placeholder: "tu@empresa.com",

        // Users
        users_title: "Gestión de Usuarios",
        users_desc: "Administra los usuarios del sistema",
        create_user: "Crear Usuario",
        edit_user: "Editar Usuario",
        user_list: "Lista de Usuarios",
        user_list_desc: "Todos los usuarios registrados en el sistema",
        name: "Nombre",
        full_name: "Nombre Completo",
        phone: "Teléfono",
        role: "Rol",
        status: "Estado",
        total_users: "Total Usuarios",
        admins: "Administradores",
        engineers: "Ingenieros",
        inspectors: "Inspectores",
        active: "Activo",
        inactive: "Inactivo",
        company_email: "Correo de la Empresa",
        password_min: "Mínimo 8 caracteres",
        user_created: "Usuario creado",
        user_updated: "Usuario actualizado",
        user_deleted: "Usuario eliminado",

        // Machines
        machines_title: "Gestión de Máquinas",
        machines_desc: "Administra las máquinas del sistema",
        create_machine: "Crear Máquina",
        edit_machine: "Editar Máquina",
        machine_list: "Lista de Máquinas",
        machine_list_desc: "Todas las máquinas registradas en el sistema",
        cmm: "CMM",
        line: "Línea",
        process: "Proceso",
        creation_date: "Fecha de Creación",
        total_machines: "Total Máquinas",
        with_line: "Con Línea",
        with_process: "Con Proceso",
        no_machines: "No hay máquinas registradas",
        create_first_machine: "Crea la primera máquina para comenzar",
        machine_created: "Máquina creada",
        machine_updated: "Máquina actualizada",
        machine_deleted: "Máquina eliminada",
        showing_machines: "Mostrando {start} - {end} de {total} máquinas",
        showing_items: "Mostrando {start} - {end} de {total} {items}",
        label_users: "usuarios",
        label_machines: "máquinas",
        label_alerts: "alertas",
        page_of: "Página {current} de {total}",
        previous: "Anterior",
        next: "Siguiente",
        unknown_name: "Sin nombre",
        required_fields: "Todos los campos son obligatorios",
        error_create_machine: "No se pudo crear la máquina",
        error_update_machine: "No se pudo actualizar la máquina",
        error_delete_machine: "No se pudo eliminar la máquina",

        // Alerts
        alerts_title: "Gestión de Alertas",
        alerts_desc: "Historial completo de alertas del sistema",
        refresh: "Actualizar",
        filters: "Filtros",
        alert_list: "Lista de Alertas",
        no_alerts: "No hay alertas",
        no_alerts_filters: "No se encontraron alertas con los filtros seleccionados",
        system_ok: "El sistema está funcionando correctamente",
        pending: "Pendientes",
        acknowledged: "Reconocidas",
        resolved: "Resueltas",
        search_placeholder: "Buscar por item, columna...",
        all_machines: "Todas las máquinas",
        all_statuses: "Todos los estados",
        status_pending: "Pendiente",
        status_acknowledged: "Reconocido",
        status_resolved: "Resuelto",
        date_range: "Rango de fechas",
        clear_filters: "Limpiar filtros",
        critical: "Crítico",
        warning: "Advertencia",
        info: "Info",
        comment_placeholder: "Comentario para reconocer (requerido)...",
        resolve_note_placeholder: "Nota para resolver (requerido)...",
        acknowledge_button: "Reconocer",
        resolve_button: "Resolver",
        alert_below_lower: "El valor {value} debajo del límite inferior",
        alert_above_upper: "El valor {value} supera el límite superior",
        alert_out_of_spec: "El valor {value} fuera de especificación",
        alert_out_of_control: "El valor {value} fuera de control",
        alert_trend: "Tendencia detectada en valor {value}",
        alert_default: "Alerta - {type}",
        nominal: "Nominal",
        limits: "Límites",
        severity: "Severidad",
        date: "Fecha",
        alert: "Alerta",
        machine: "Máquina",
        error_loading_stats: "Error al cargar estadísticas de alertas",

        // Dashboard
        dashboard_title: "Dashboard de Máquinas",
        dashboard_desc: "Monitoreo en tiempo real del rendimiento de las máquinas",
        machines_found: "máquinas encontradas",
        select_dates: "Seleccionar fechas...",
        last_7_days: "Últimos 7 días",
        last_30_days: "Últimos 30 días",
        apply: "Aplicar",
        select_machine: "Seleccionar máquina...",
        search_machine: "Buscar máquina...",
        no_machines_found: "No se encontraron máquinas.",
        spc_title: "Control Estadístico de Procesos (SPC)",
        spc_desc: "Gráfico de control para la máquina",
        measurement: "Medición",
        select_process: "Seleccionar proceso...",
        search_process: "Buscar proceso...",
        loading_spc: "Cargando datos SPC...",
        no_process_selected: "Selecciona un proceso",
        no_spc_data: "No hay datos SPC disponibles",
        data_points: "Puntos de datos",
        non_conformant: "No Conformes",
        within_spec: "Dentro de Spec",
        out_of_spec: "Fuera de Spec",
        capability_histogram: "Histograma de Capacidad",
        distribution_desc: "Distribución de mediciones con límites de especificación y control",
        period: "Período",
        connection_error: "Error de conexión",
        retry: "Reintentar"
    },
    en: {
        // Nav & Common
        dashboard: "Dashboard",
        users: "User Management",
        machines: "Machine Management",
        alerts: "Alerts",
        settings: "Settings",
        logout: "Logout",
        language: "Language",
        theme: "Theme",
        appearance: "Appearance",
        general: "General Settings",
        notifications: "Notifications",
        security: "Security",
        api: "API Configuration",
        error: "Error",
        success: "Success",
        cancel: "Cancel",
        save: "Save",
        save_configuration: "Save Configuration",
        config_saved: "Configuration saved",
        config_saved_desc: "Changes have been applied successfully",
        create: "Create",
        update: "Update",
        delete: "Delete",
        actions: "Actions",
        loading: "Loading...",
        none: "None",
        all: "All",
        company_name: "Company Name",
        company_name_placeholder: "Company name",
        timezone: "Timezone",
        refresh_interval: "Refresh Interval (seconds)",
        maintenance_alerts: "Maintenance Alerts",
        maintenance_alerts_desc: "Receive notifications when maintenance is required",
        temperature_alerts: "Temperature Alerts",
        temperature_alerts_desc: "Notify when temperature exceeds limits",
        daily_reports: "Daily Reports",
        daily_reports_desc: "Send daily summary via email",
        session_timeout: "Session Timeout (minutes)",
        "2fa": "Two-Factor Authentication",
        "2fa_desc": "Require additional verification for access",
        audit_log: "Audit Log",
        audit_log_desc: "Keep log of all user actions",
        api_endpoint: "API Endpoint",
        api_endpoint_placeholder: "API Endpoint URL",
        api_timeout: "API Timeout (seconds)",
        auto_retries: "Automatic Retries",
        auto_retries_desc: "Automatically retry failed calls",
        light: "Light",
        dark: "Dark",
        system: "System",
        general_desc: "Basic system configuration",
        notifications_desc: "Configure system alerts and notifications",
        security_desc: "Security and access settings",
        api_desc: "External connection settings",
        appearance_desc: "Customize system appearance",

        // Login
        welcome_title: "Industrial System",
        welcome_desc: "Sign in to access the system",
        email: "Email",
        password: "Password",
        login_button: "Sign In",
        login_loading: "Signing in...",
        login_error: "Authentication Error",
        login_error_desc: "Incorrect email or password",
        enter_email_password: "Enter your email and password",
        email_placeholder: "you@company.com",

        // Users
        users_title: "User Management",
        users_desc: "Manage system users",
        create_user: "Create User",
        edit_user: "Edit User",
        user_list: "User List",
        user_list_desc: "All registered users in the system",
        name: "Name",
        full_name: "Full Name",
        phone: "Phone",
        role: "Role",
        status: "Status",
        total_users: "Total Users",
        admins: "Admins",
        engineers: "Engineers",
        inspectors: "Inspectors",
        active: "Active",
        inactive: "Inactive",
        company_email: "Company Email",
        password_min: "Minimum 8 characters",
        user_created: "User created",
        user_updated: "User updated",
        user_deleted: "User deleted",

        // Machines
        machines_title: "Machine Management",
        machines_desc: "Manage system machines",
        create_machine: "Create Machine",
        edit_machine: "Edit Machine",
        machine_list: "Machine List",
        machine_list_desc: "All registered machines in the system",
        cmm: "CMM",
        line: "Line",
        process: "Process",
        creation_date: "Creation Date",
        total_machines: "Total Machines",
        with_line: "With Line",
        with_process: "With Process",
        no_machines: "No machines registered",
        create_first_machine: "Create the first machine to get started",
        machine_created: "Machine created",
        machine_updated: "Machine updated",
        machine_deleted: "Machine deleted",
        showing_machines: "Showing {start} - {end} of {total} machines",
        showing_items: "Showing {start} - {end} of {total} {items}",
        label_users: "users",
        label_machines: "machines",
        label_alerts: "alerts",
        page_of: "Page {current} of {total}",
        previous: "Previous",
        next: "Next",
        unknown_name: "Unnamed",
        required_fields: "All fields are required",
        error_create_machine: "Could not create machine",
        error_update_machine: "Could not update machine",
        error_delete_machine: "Could not delete machine",

        // Alerts
        alerts_title: "Alert Management",
        alerts_desc: "Complete system alert history",
        refresh: "Refresh",
        filters: "Filters",
        alert_list: "Alert List",
        no_alerts: "No alerts",
        no_alerts_filters: "No alerts found with selected filters",
        system_ok: "System is operating correctly",
        pending: "Pending",
        acknowledged: "Acknowledged",
        resolved: "Resolved",
        search_placeholder: "Search by item, column...",
        all_machines: "All machines",
        all_statuses: "All statuses",
        status_pending: "Pending",
        status_acknowledged: "Acknowledged",
        status_resolved: "Resolved",
        date_range: "Date Range",
        clear_filters: "Clear filters",
        critical: "Critical",
        warning: "Warning",
        info: "Info",
        comment_placeholder: "Comment to acknowledge (required)...",
        resolve_note_placeholder: "Note to resolve (required)...",
        acknowledge_button: "Acknowledge",
        resolve_button: "Resolve",
        alert_below_lower: "Value {value} below lower limit",
        alert_above_upper: "Value {value} above upper limit",
        alert_out_of_spec: "Value {value} out of spec",
        alert_out_of_control: "Value {value} out of control",
        alert_trend: "Trend detected in value {value}",
        alert_default: "Alert - {type}",
        nominal: "Nominal",
        limits: "Limits",
        severity: "Severity",
        date: "Date",
        alert: "Alert",
        machine: "Machine",
        error_loading_stats: "Error loading alert statistics",

        // Dashboard
        dashboard_title: "Machine Dashboard",
        dashboard_desc: "Real-time machine performance monitoring",
        machines_found: "machines found",
        select_dates: "Select dates...",
        last_7_days: "Last 7 days",
        last_30_days: "Last 30 days",
        apply: "Apply",
        select_machine: "Select machine...",
        search_machine: "Search machine...",
        no_machines_found: "No machines found.",
        spc_title: "Statistical Process Control (SPC)",
        spc_desc: "Control chart for machine",
        measurement: "Measurement",
        select_process: "Select process...",
        search_process: "Search process...",
        loading_spc: "Loading SPC data...",
        no_process_selected: "Select a process",
        no_spc_data: "No SPC data available",
        data_points: "Data points",
        non_conformant: "Non-Conformant",
        within_spec: "Within Spec",
        out_of_spec: "Out of Spec",
        capability_histogram: "Capability Histogram",
        distribution_desc: "Measurement distribution with specification and control limits",
        period: "Period",
        connection_error: "Connection Error",
        retry: "Retry"
    }
}

const LanguageProviderContext = createContext<LanguageProviderState>(initialState)

export function LanguageProvider({
    children,
    defaultLanguage = "es",
    storageKey = "vite-ui-language",
}: LanguageProviderProps) {
    const [language, setLanguage] = useState<Language>(
        () => (localStorage.getItem(storageKey) as Language) || defaultLanguage
    )

    useEffect(() => {
        localStorage.setItem(storageKey, language)
    }, [language])

    const t = (key: string) => {
        const langData = translations[language] as Record<string, string>;
        return langData[key] || key;
    }

    const value = {
        language,
        setLanguage,
        t
    }

    return (
        <LanguageProviderContext.Provider value={value}>
            {children}
        </LanguageProviderContext.Provider>
    )
}

export const useLanguage = () => {
    const context = useContext(LanguageProviderContext)

    if (context === undefined)
        throw new Error("useLanguage must be used within a LanguageProvider")

    return context
}
