// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilzsxsbgxkxcaujkvasz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsenN4c2JneGt4Y2F1amt2YXN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NjM4MDMsImV4cCI6MjA3MTAzOTgwM30.3jHVktWu8Ahxgrpl3guX8KRGZW0SzUHH7ealSBzntHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});